type: "transformation"
version: "1.0"
pipeline:
  components:
    MOCK_DATA:
      type: "table-input"
      parameters:
        componentName: "MOCK_DATA"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "MOCK_DATA"
        columnNames:
        - "ID"
        - "FIRST_NAME"
        - "LAST_NAME"
        - "EMAIL"
        - "CONTACT"
        - "ADDRESS"
        timeOffset:
    SQL:
      type: "sql"
      sources:
      - "MOCK_DATA"
      parameters:
        componentName: "SQL"
        query: "WITH data_validation AS (\r\n    SELECT *\r\n    FROM mock_data\r\n\
          \    WHERE \r\n        -- Name validations\r\n        first_name IS NOT\
          \ NULL AND last_name IS NOT NULL\r\n        AND LENGTH(first_name) >= 3\
          \ AND LENGTH(first_name) <= 20\r\n        AND LENGTH(last_name) >= 3 AND\
          \ LENGTH(last_name) <= 20\r\n        AND first_name = TRIM(first_name)\r\
          \n        AND last_name = TRIM(last_name)\r\n        AND first_name != ''\
          \ AND last_name != ''\r\n        AND first_name = INITCAP(first_name)\r\n\
          \        AND last_name = INITCAP(last_name)\r\n        AND first_name REGEXP\
          \ '^[A-Z][a-z]+$'\r\n        AND last_name REGEXP '^[A-Z][a-z]+$'\r\n\r\n\
          \        -- Email validations\r\n        AND email IS NOT NULL AND email\
          \ != ''\r\n        AND LENGTH(email) >= 5 AND LENGTH(email) <= 40\r\n  \
          \      AND email = TRIM(email)\r\n        AND email REGEXP '^[A-Za-z][A-Za-z0-9]+@[A-Za-z]+\\\
          .[A-Za-z]+$'\r\n\r\n        -- Contact validations\r\n        AND contact\
          \ IS NOT NULL AND contact != ''\r\n        AND contact REGEXP '^[0-9]{3}-[0-9]{3}-[0-9]{4}+$'\r\
          \n\r\n        -- Address validations\r\n        AND address IS NOT NULL\
          \ AND address != ''\r\n        AND address REGEXP '^[0-9]+ [A-Za-z ]+$'\r\
          \n)\r\nSELECT * FROM data_validation\r\n"
    FILTERED_MOCK_DATA:
      type: "table-output"
      sources:
      - "SQL"
      parameters:
        componentName: "FILTERED_MOCK_DATA"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "FILTERED_MOCK_DATA"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "ID"
          - "ID"
        - - "FIRST_NAME"
          - "FIRST_NAME"
        - - "LAST_NAME"
          - "LAST_NAME"
        - - "EMAIL"
          - "EMAIL"
        - - "CONTACT"
          - "CONTACT"
        - - "ADDRESS"
          - "ADDRESS"
        orderBy:
        outputMode: "Truncate"
design:
  components:
    MOCK_DATA:
      position:
        x: -440
        "y": -70
      tempMetlId: 1
    SQL:
      position:
        x: -320
        "y": -70
      tempMetlId: 2
    FILTERED_MOCK_DATA:
      position:
        x: -200
        "y": -70
      tempMetlId: 3
