type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "table1_metadata"
      parameters:
        componentName: "Start"
    table1_metadata:
      type: "table-metadata-to-grid"
      transitions:
        success:
        - "table2_metadata"
      parameters:
        componentName: "table1_metadata"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        gridVariable: "table1_metadata"
        gridVariableMapping:
        - "Name"
        - "Database Type"
        targetTable: "FLIGHTS_DATA"
    table2_metadata:
      type: "table-metadata-to-grid"
      transitions:
        success:
        - "metadata_comparison"
      parameters:
        componentName: "table2_metadata"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        gridVariable: "table2_metadata"
        gridVariableMapping:
        - "Name"
        - "Database Type"
        targetTable: "FLIGHTS_DATA_FILTERED"
    metadata_comparison:
      type: "python-pushdown"
      transitions:
        unconditional:
        - "If"
      parameters:
        componentName: "metadata_comparison"
        externalAccessIntegrations:
        packages:
        scriptLocation: "Component"
        pythonScript: |-
          if table1_metadata == table2_metadata:
              context.updateVariable('test1',1)
          else:
              context.updateVariable('test1',0)

          print('table1\t',table1_metadata, '\ntable2\t', table2_metadata)
        scriptTimeout: "360"
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"
    End Failure:
      type: "end-failure"
      parameters:
        componentName: "End Failure"
    If:
      type: "if"
      transitions:
        failure:
        - "End Failure"
        "true":
        - "End Success"
      parameters:
        componentName: "If"
        mode: "Simple"
        condition:
        - - "test1"
          - "Is"
          - "Equal to"
          - "1"
        combineConditions: "And"
  variables:
    table1_metadata:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          name:
            columnType: "TEXT"
          type:
            columnType: "TEXT"
      defaultValue: []
    table2_metadata:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          name:
            columnType: "TEXT"
          type:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -410
        "y": -10
      tempMetlId: 1
    table1_metadata:
      position:
        x: -290
        "y": -10
      tempMetlId: 2
    table2_metadata:
      position:
        x: -160
        "y": -10
      tempMetlId: 3
    metadata_comparison:
      position:
        x: -20
        "y": -10
      tempMetlId: 4
    End Success:
      position:
        x: 300
        "y": -50
      tempMetlId: 7
    End Failure:
      position:
        x: 310
        "y": 40
      tempMetlId: 8
    If:
      position:
        x: 100
        "y": -10
      tempMetlId: 9
